In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in range(2, 7):
    print(i)

2
3
4
5
6


In [ ]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [ ]:
list_1 = []

for i in range(10):
    list_1.append(i)
    list_1.append(i+1)
    list_1.append(i+2)

print(list_1)
print(list_1[0])
list_1[3]

[0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6, 7, 6, 7, 8, 7, 8, 9, 8, 9, 10, 9, 10, 11]
0


1

In [ ]:
i=0
while i<7:
  print(i)
  i=i+1

0
1
2
3
4
5
6


In [ ]:
user_input = ''
while user_input.lower() != 'quit':
    user_input = input("Enter something (type 'quit' to stop): ")
    print("You entered:", user_input)

Enter something (type 'quit' to stop): 2
You entered: 2
Enter something (type 'quit' to stop): quit
You entered: quit


In [ ]:
def greet():
    print('Day 2 8/7/26')
greet()
print('Outside function')

Day 2 8/7/26
Outside function


In [ ]:
def find_square(num):
    result = num * num
    return result
square = find_square(25)
print('Square:', square)

Square: 625


In [ ]:
def user():
  i=0
  for i in range(2, 7):
    print(i)
  while i < 3:
    print("Day2 Internship")
user()

2
3
4
5
6


In [ ]:
def something(i, j):
    mul = i * i
    div = mul / j

    list_1 = []

    for i in range(mul):
        list_1.append(i)
        print(list_1)

    list_1 = []

    while j < 3:
        print(j)
        j = j + 1

    return mul, div
something(2,2)

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
2


(4, 2.0)

In [ ]:
import numpy as np
d_0 = np.array(42) #0d
d_1 = np.array([42,421,423,424]) #1d
d_2 = np.array([  #2d
    [1,2,3],
    ('t', 'u', 'p',),
    ('t', 'u', 'p',),
    ('t', 'u', 'p',),
    ('t', 'u', 'p',)
])

d_3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9] ],

               [
                   [10,12,14],
                   [15,18,30],
                   [33,35,36]
               ]
]
)

In [ ]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([42, 421, 423, 424])

d_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d_3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],

    [
        [10,12,14],
        [15,18,30],
        [33,35,36]
    ]
])

print("Size of d3 is: ", d_3.size)
print("Dimensions of d3 are: ", d_3.ndim)

flattened_array = d_2.flatten()
print("Dimensions of flattened array is ", flattened_array.ndim)
print("Size of flattened array is: ", flattened_array.size)

Size of d3 is:  18
Dimensions of d3 are:  3
Dimensions of flattened array is  1
Size of flattened array is:  9


In [ ]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([42, 421, 423, 424])

d_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d_3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])


print(np.ndim(d_0), d_0)
print(np.ndim(d_1), d_1)
print(np.ndim(d_2), d_2)
print(np.ndim(d_3), d_3)

0 42
1 [ 42 421 423 424]
2 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
import numpy as np

# 1-D Array
a = np.array([10, 20, 30, 40, 50])
print("1-D Array:")
print(a)

# 2-D Array
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2-D Array:")
print(b)

# 3-D Array
d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print("\n3-D Array:")
print(d)

# Accessing elements
print("\nElement at d[1,2,1] =", d[1,2,1])
print("Element at d[0,1,2] =", d[0,1,2])

# Array properties
print("\nShape:", d.shape)
print("Size:", d.size)
print("Dimensions:", d.ndim)

# Reshape
reshaped = d.reshape(3, 6)
print("\nReshaped Array:")
print(reshaped)

# Flatten
flattened = d.flatten()
print("\nFlattened Array:")
print(flattened)

1-D Array:
[10 20 30 40 50]

2-D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3-D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Element at d[1,2,1] = 17
Element at d[0,1,2] = 6

Shape: (2, 3, 3)
Size: 18
Dimensions: 3

Reshaped Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
import numpy as np

# Create a multidimensional array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Array:")
print(arr)

# Access values using index numbers
print("\nAccessing Elements:")
print("Element at [0][1]:", arr[0][1])
print("Element at [2][2]:", arr[2][2])

# Mathematical operations
sum_values = arr[0][1] + arr[2][2]
product = arr[1][0] * arr[0][2]

print(sum_values)
print(product)

# NumPy methods
print("\nNumPy Methods:")

print("1. Sum:", np.sum(arr))
print("2. Minimum:", np.min(arr))
print("3. Maximum:", np.max(arr))
print("4. Mean:", np.mean(arr))
print("5. Transpose:", arr.T)
print("6. Sorted Array:", np.sort(arr))

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Accessing Elements:
Element at [0][1]: 2
Element at [2][2]: 9
11
12

NumPy Methods:
1. Sum: 45
2. Minimum: 1
3. Maximum: 9
4. Mean: 5.0
5. Transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
6. Sorted Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
